Update to v0.9.7
AnacondaRecipes/pytest-sugar-feedstock pull request #2
Opened 2023-05-16 23:24 UTC by Jrice1317

2023-05-16 23:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_8awy7zjd_f/clone/recipe/meta.yaml:26: python_build_tool_in_run: The python build tool packaging is in run depends
Warnings were found

</details>

2023-05-17 15:55 UTC, Arishamays1 approved these changes
LGTM

2023-05-17 18:50 UTC, ViridianMelody requested changes

2023-05-17 18:50 UTC, ViridianMelody commented on recipe/meta.yaml
> +    - poetry-core
```suggestion
```
`poetry-core` isn't used since we're installing with `pip`.

2023-05-17 19:20 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - poetry-core
Side note: poetry-core can be used, but isn't for this specific package. the `pyproject.toml` doesn't specify any build time dependencies, which means the default build backed is setuptools.

2023-05-17 20:16 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_38lgpsm8o6/clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool packaging is in run depends
Warnings were found

</details>

2023-05-17 20:54 UTC, ViridianMelody approved these changes

2023-05-17 22:56 UTC, ELundby45 approved these changes

2023-05-18 02:47 UTC, merged

2023-05-18 02:48 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_3fap_ps_cn/clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool packaging is in run depends
Warnings were found

</details>